(in-package :cicili)

;; deeply traverse spec tree to find lexeme id for a storage
(defun deep-storageof-name (id full-name spec)
  (format t "STORAGEOF REQUESTED: ~A~%" spec)
  (if spec
      (let ((const-val (construct spec)))
        (cond ((eql const-val '|@ATOM|)
               (cond ((eql (typeof spec) '|@SYMBOL|) (*gets* (name spec)))
                     (t spec)))
              ((eql const-val '|@VAR|)   spec)
              ((eql const-val '|@PARAM|) spec)
              ((eql const-val '|@FUNC|)  spec)
              ((eql const-val '|@UNARY|)
               (cond ((eql (name spec) '&) nil)
                     ((eql (name spec) '*)
                      (let ((ty (deep-storageof-name id full-name (default spec))))
                        (if ty
                            (let* ((storage-id (intern (format nil "cof/~A~:[~{~A~^/~}~;~*~]" (name ty) full-name full-name)))
                                   (storage (*gets* storage-id)))
                              (format t "COCOCOCOCOCOCOCOCOCOF1 ~A  ~A~%" (typeof ty) ty)
                              (if storage
                                  storage
                                  (let* ((modifier (modifier ty))
                                         (mod-val (cond
                                                    ((key-eq '|ref| modifier)  '|move|)
                                                    ((key-eq '|***| modifier)  '|**|)
                                                    ((key-eq '|**|  modifier)  '|*|)
                                                    ((key-eq '|*|   modifier)  (when (is-non-copy (typeof ty)) '|move|))
                                                    ((is-non-copy (typeof ty)) '|move|)
                                                    (t (error (format nil "'cof not allowed for: ~A~%  in: ~A" ty spec)))))
                                         (ptr-mod (cond
                                                    ((null mod-val) nil)
                                                    ((key-eq '|move| mod-val) nil)
                                                    ((key-eq '|ref|  mod-val) nil)
                                                    (t (const-ptr ty))))
                                         (new-storage (make-specifier (name ty) (construct ty) (const ty) (typeof ty)
                                                                      mod-val ptr-mod (array-def ty)
                                                                      nil nil (anonymous ty))))
                                    (format t "COCOCOCOCOCOCOCOCOCOF2 ~A  ~A~%" (is-non-copy (typeof ty)) new-storage)
                                    (*puts* storage-id new-storage))))
                            nil)))
                     (t nil)))
              ((or (eql const-val '|@$|) (eql const-val '|@->|))
               (let ((struct (deep-storageof-name id (cons (name spec) full-name) (name spec))))
                 (when struct
                   (format t "STRUCTTTT11 ~A   ~A~%" (typeof struct) struct)
                   (let* ((storage-id (intern (format nil "~A/~A" (name (default spec)) (name struct))))
                          (storage (*gets* storage-id)))
                     (if storage
                         storage
                         (let ((end-type (if (typep (typeof struct) 'sp)
                                             (deep-typeof "" (typeof struct))
                                             (deep-typeof (typeof struct)))))
                           (unless end-type (error "unknown struct type: ~A~%  accessed in: ~A~%" (typeof struct) spec))
                           (format t "STRUCTTTT22 ~A~%" end-type)
                           (setq storage-id (intern (format nil "~A/~A"  (name (default spec)) (typeof end-type))))
                           (setq storage (*gets* storage-id))
                           (format t "STRUCTTTT22 STORAGE ~A, ~A~%" storage-id storage)
                           (let ((new-storage (make-specifier storage-id (construct storage) (const storage) (typeof storage)
                                                              (modifier storage) (const-ptr storage) (array-def storage)
                                                              (default storage) (attrs storage) (anonymous storage))))
                             (*puts* storage-id new-storage))))))))
              ((eql const-val '|@CAST|)   (deep-storageof-name id (cons (name spec) full-name) (default spec)))
              ((eql const-val '|@RETURN|) (deep-storageof-name id (cons (name spec) full-name) (default spec)))
              ((eql const-val '|@TYPEOF|)
               (deep-storageof-name id (cons (name spec) full-name) (default spec))
               ;; (combine-types (deep-storageof-name id (cons (name spec) full-name) (default spec)) spec)
               )
              (t nil)))
      nil))

(defun deep-storageof (id &optional spec)
  (let ((spec (if spec spec (*gets* id))))
      (deep-storageof-name id (list (name spec)) spec)))

;; deeply traverse spec tree to find lexeme id for a type
;; type inference back-end
(defun deep-typeof (id &optional spec too-deep)
  (let ((deep-res 
            (let* ((id (if (and (listp id) (key-eq (car id) '|struct|)) (cadr id) id))
                   (spec (if spec spec (*gets* id))))
              (format t "TYPEOF REQUESTED: ~A~%" spec)
              (if spec
                  (let ((const-val (construct spec)))
                    (cond ((eql const-val '|@ATOM|)
                           (cond ((eql (typeof spec) '|@SYMBOL|) (*gets* (name spec)))
                                 (t spec)))
                          ((key-eq (typeof spec) '|auto|) (deep-typeof id (default spec))) ; var or param
                          ((eql const-val '|@CALL|)
                           (let ((name-val (name spec)))
                             (if (typep name-val 'sp) (deep-typeof id name-val) (*gets* name-val))))
                          ((eql const-val '|@VAR|) spec)
                          ((eql const-val '|@PARAM|) spec)
                          ((eql const-val '|@FUNC|) spec)
                          ((eql const-val '|@LETN|)
                           (*push* (name spec))
                           (*pop* (deep-typeof id (car (last (body (body spec)))))))
                          ((eql const-val '|@PROGN|)
                           (*push* (name spec))
                           (*pop* (deep-typeof id (car (last (body (body spec)))))))
                          ((eql const-val '|@?|) (deep-typeof id (car (default spec))))
                          ((eql const-val '|@UNARY|)
                           (let ((ty (deep-storageof-name id '() spec)))
                             (format t "UUUUUUUUNARYYYYYYYYYYY2 ~A~%" ty)                   
                             (if ty
                                 (cond ((eql (name spec) '&) ty)
                                       ;; (let ((tmp-type-infer-time (prog1 *type-infer-time-var*
                                       ;;                                  (setq *type-infer-time-var* t)))
                                       ;;       (new_spec (specify-variable (let ((tmp-name (if (name ty) (name ty) (GENSYM "AOF"))))
                                       ;;                                     (append (list '|var|)
                                       ;;                                       (infer-type (list '|aof| tmp-name) :with-name tmp-name)))
                                       ;;                   '())))
                                       ;;   (setq *type-infer-time-var* tmp-type-infer-time)
                                       ;;   (setf (is-moved new_spec) (is-moved ty))
                                       ;;   new_spec))
                                       ((eql (name spec) '*) ty)
                                       ;; (let ((tmp-type-infer-time (prog1 *type-infer-time-var*
                                       ;;                                  (setq *type-infer-time-var* t)))
                                       ;;       (new_spec (specify-variable (let ((tmp-name (if (name ty) (name ty) (GENSYM "COF"))))
                                       ;;                                     (append (list '|var|)
                                       ;;                                       (infer-type (list '|cof| tmp-name) :with-name tmp-name)))
                                       ;;                   '())))
                                       ;;   (setq *type-infer-time-var* tmp-type-infer-time)
                                       ;;   (setf (is-moved new_spec) (is-moved ty))
                                       ;;   new_spec))
                                       (t ty))
                                 nil)))
                          ((eql const-val '|@OPR|) (deep-typeof id (car (default spec))))
                          ((or (eql const-val '|@$|) (eql const-val '|@->|))
                           (let ((struct (deep-typeof id (name spec))))
                             (when struct
                               (format t "STRUCTTTT1 ~A   ~A~%" (typeof struct) struct)
                               (let ((end-type (deep-typeof (typeof struct))))
                                 (unless end-type (error "unknown struct type: ~A~%  accessed in: ~A~%" (typeof struct) spec))
                                 (format t "STRUCTTTT2 ~A~%" end-type)
                                 (*gets* (intern (format nil "~A/~A"  (name (default spec)) (typeof end-type))))))))
                          ((eql const-val '|@TYPEDEF|)
                           (deep-typeof (typeof spec))
                           ;; (combine-types (deep-typeof (typeof spec)) spec)
                           )
                          ((eql const-val '|@STRUCT|) spec)
                          ((eql const-val '|@CAST|) spec)
                          ((eql const-val '|@RETURN|) (deep-typeof id (default spec)))
                          ((eql const-val '|@TYPEOF|)
                           (deep-typeof id (default spec))
                           ;; (combine-types (deep-typeof id (default spec)) spec)
                           )
                          (t nil)))
                  nil))))
    ;; (if (or too-deep (and deep-res (key-eq (construct deep-res) '|@TYPEOF|)))
    (if too-deep
        (if (and spec deep-res)
            (if (or (eql deep-res spec) (key-eq (typeof deep-res) (typeof spec)))
                deep-res
                (deep-typeof (typeof deep-res)))
            (if (and deep-res (not (eql (construct deep-res) '|@STRUCT|)))
                (deep-typeof (typeof deep-res))
                deep-res))
        deep-res)))


(defun combine-modifiers (base type bm tm)
  (cond
    ((and (null bm) (null tm)) tm)
    ((and (null bm) (not (key-eq '|ref| tm)) tm))
    ((and bm (null tm)) bm)
    ((and (key-eq '|move| bm) (key-eq '|move| tm)) '|move|)
    ((and (key-eq '|move| bm) (key-eq '|ref| tm)) tm)
    ((and (or (key-eq '|ref| bm) (key-eq '|*| bm)) (key-eq '|*|  tm))  '|**|)
    ((and (or (key-eq '|ref| bm) (key-eq '|*| bm)) (key-eq '|**| tm)) '|***|)
    ((and (key-eq '|**| bm)) (key-eq '|*|  tm) '|***|)
    (t (error (format nil "invalid type combination for: ~A~%  base: ~A" type base)))))

(defun combine-types (base type)
  (if base
      (let ((def-spec (if (typep type 'sp)
                          (make-specifier (name type) (construct type) (or (const base) (const type)) (typeof base)
                                          (combine-modifiers base type (modifier base) (modifier type))
                                          (const-ptr type) (array-def type) (default type) (attrs type))
                          (make-specifier (nth 4 type) '|@VAR| (or (const base) (nth 0 type)) (typeof base)
                                          (combine-modifiers base type (modifier base) (nth 2 type))
                                          (nth 3 type) nil nil '()))))
        (format t "TYPE COMBINATOIN: ~A ~A ~A~%" base type def-spec)
        def-spec)
      type))


;; (type inference) tries to infer from lexeme id or throw error
;; without :with-name presence: compiles type without name
;; with :with-name presence but NIL: compiles with name of the spec
;; with :with-name presence non NIL: compiles with the specified name
(defun infer-type-spec (id spec &key with-name copy-name)
  (format t "INFER SPEC REQUESTED: ~A  ~A~%   WITH:~A~%" id spec with-name)
  (let* ((mod-val (modifier spec))
         (arr-val (if (array-def spec)
                      (cond
                        ((key-eq '|*|  mod-val) '|**|)
                        ((key-eq '|**| mod-val) '|***|)
                        (t '|*|))
                      nil))
         (ptr-mod (cond
                    ((null mod-val) nil)
                    ((key-eq '|move| mod-val) nil)
                    ((key-eq '|ref|  mod-val) nil)
                    (t (const-ptr spec)))))
    (let ((full-type (if with-name
                         (if copy-name (list (const     spec)
	                                         (if (and (typep (typeof spec) 'sp) (key-eq (construct (typeof spec)) '|@TYPEOF|))
                                                 ;; (infer-type-spec id (deep-typeof id (typeof spec))
                                                 ;;                  :with-name with-name :copy-name copy-name)
                                                 (deep-typeof id (typeof spec))
                                                 (typeof spec))
	                                         (if arr-val arr-val mod-val)
                                             ptr-mod
	                                         (name      spec))
                             (list (const     spec)
	                               (if (and (typep (typeof spec) 'sp) (key-eq (construct (typeof spec)) '|@TYPEOF|))
                                       ;; (infer-type-spec id (deep-typeof id (typeof spec))
                                       ;;                  :with-name with-name :copy-name copy-name)
                                       (deep-typeof id (typeof spec))
                                       (typeof spec))
	                               (if arr-val arr-val mod-val)
                                   ptr-mod
	                               with-name))
                         (list (const     spec)
	                           (if (and (typep (typeof spec) 'sp) (key-eq (construct (typeof spec)) '|@TYPEOF|))
                                   ;; (infer-type-spec id (deep-typeof id (typeof spec))
                                   ;;                  :with-name with-name :copy-name copy-name)
                                   (deep-typeof id (typeof spec))
                                   (typeof spec))
	                           (if arr-val arr-val mod-val)
                               ptr-mod
                               nil))))
      (values (remove nil full-type) full-type))))

;; type inference front-end, exported
(defun infer-type (id &key with-name copy-name)
  (format t "INFER REQUESTED: ~A    WITH:~A~%" id with-name)
  (let* ((id (expand-macros id))
         (spec (cond ((numberp id) (return-from infer-type
                                     (values (list '|const| '|int| with-name)
                                             (list '|const| '|int| NIL NIL with-name))))
                     ((stringp id) (specify-cast-expr (list '|cast| (list '|const| '|char| '[]) id)))
                     ((listp id) (let* ((clause (expand-macros id))
                                        (func (expand-macros (car clause))))
                                   (setq clause (expand-macros (append (list func) (cdr clause))))
                                   (setq func (expand-macros (car clause)))
                                   (format t "TTTTT ~A   of    ~A~%" func clause)
                                   (cond ((key-eq func '|cast|)
                                          (let ((expr (specify-cast-expr clause)))
                                            (format t "EEEEE ~A~%" expr)
                                            expr))
                                         ((and (listp func) (eql (car func) '|QUOTE|))
                                          (let ((func (cadr func)))
                                            (if (key-eq (car func) '|lambda|)
                                                (let ((out (nth 2 func)))
                                                  (if (key-eq (car out) '|out|)
                                                      (let ((out-ext (expand-macros (cadr out))))
                                                        (if (key-eq out-ext '|auto|)
                                                            (let ((ret-val (find-clause '|return| (nthcdr 2 func))))
                                                              (format t "GOUTOUTOUTOUT1 ~A~%" ret-val)
                                                              (return-from infer-type
                                                                (infer-type ret-val
                                                                  :with-name with-name :copy-name copy-name)))
                                                            (return-from infer-type
                                                              (infer-type out-ext
                                                                :with-name with-name :copy-name copy-name))))
                                                      (list '|void|)))
                                                (if (key-eq (car func) '|lambda*|)
                                                    (let ((out (nth 3 func)))
                                                      (if (key-eq (car out) '|out|)
                                                          (let ((out-ext (expand-macros (cadr out))))
                                                            (if (key-eq out-ext '|auto|)
                                                                (let ((ret-val (find-clause '|return| (nthcdr 3 func)))
                                                                      (tmp-type-infer-time (prog1 *type-infer-time-lambda*
                                                                                             (setq *type-infer-time-lambda* t)))
                                                                      (lamb-spec (specify-function func '())))
                                                                  (setq *type-infer-time-lambda* tmp-type-infer-time)
                                                                  (format t "GOUTOUTOUTOUT2 ~A~%" ret-val)
                                                                  (return-from infer-type
                                                                    (infer-type-spec "" lamb-spec
                                                                                     :with-name with-name :copy-name copy-name)))
                                                                (return-from infer-type
                                                                  (infer-type out-ext
                                                                    :with-name with-name :copy-name copy-name))))
                                                          (list '|void|)))))))
                                         ((key-eq func '|letn|)
                                          (let ((tmp-type-infer-time (prog1 *type-infer-time-lambda*
                                                                       (setq *type-infer-time-lambda* t)))
                                                (letn-spec (specify-let clause)))
                                            (setq *type-infer-time-lambda* tmp-type-infer-time)
                                            (*push* (name letn-spec))
                                            (format t "RRRRR1 ~A~%" (expand-macros (car (last clause))))
                                            (let ((ty (multiple-value-list (infer-type (expand-macros (car (last clause)))
                                                                             :with-name with-name :copy-name copy-name))))
                                              (*pop* ty)
                                              (return-from infer-type (values-list ty)))))
                                         ((key-eq func '|progn|)
                                          (let ((tmp-type-infer-time (prog1 *type-infer-time-lambda*
                                                                       (setq *type-infer-time-lambda* t)))
                                                (progn-spec (specify-progn clause)))
                                            (setq *type-infer-time-lambda* tmp-type-infer-time)
                                            (*push* (name progn-spec))
                                            (format t "RRRRR2 ~A~%" (expand-macros (car (last clause))))
                                            (let ((ty (multiple-value-list (infer-type (expand-macros (car (last clause)))
                                                                             :with-name with-name :copy-name copy-name))))
                                              (*pop* ty)
                                              (return-from infer-type (values-list ty)))))
                                         ((key-eq func '|aof|)
                                          (format t "RRRRR3 ~A~%" (expand-macros (cadr clause)))
                                          (return-from infer-type
                                            (let ((ty (infer-type (expand-macros (cadr clause))
                                                        :with-name with-name :copy-name copy-name)))
                                              (multiple-value-bind (const typeof modifier const-ptr variable array)
		                                          (specify-type< ty)
                                                (let ((ty-def (list const typeof
                                                                    (cond
                                                                      ((null modifier)           '|*|)
                                                                      ((key-eq '|*|    modifier) '|**|)
                                                                      ((key-eq '|**|   modifier) '|***|)
                                                                      ((key-eq '|move| modifier) '|ref|)
                                                                      (t (error (format nil "'aof not allowed for: ~A~%  in ~A" ty clause))))
                                                                    const-ptr variable array)))
                                                  (values (remove nil ty-def) ty-def))))))
                                         ((key-eq func '|cof|)
                                          (format t "RRRRR4 ~A~%" (expand-macros (cadr clause)))
                                          (return-from infer-type
                                            (let ((ty (infer-type (expand-macros (cadr clause))
                                                        :with-name with-name :copy-name copy-name)))
                                              (multiple-value-bind (const typeof modifier const-ptr variable)
		                                          (specify-type< ty)
                                                (let* ((mod-val (cond
                                                                  ((key-eq '|ref| modifier) '|move|)
                                                                  ((key-eq '|***| modifier) '|**|)
                                                                  ((key-eq '|**|  modifier) '|*|)
                                                                  ((key-eq '|*|   modifier)  (when (is-non-copy typeof) '|move|))
                                                                  ((is-non-copy typeof '|move|))
                                                                  ((key-eq '|*|   modifier) nil)
                                                                  (t (error (format nil "'cof not allowed for: ~A~%  in: ~A" ty clause)))))
                                                       (ptr-mod (cond
                                                                  ((null mod-val) nil)
                                                                  ((key-eq '|move| mod-val) nil)
                                                                  ((key-eq '|ref|  mod-val) nil)
                                                                  (t const-ptr)))
                                                       (ty-def (list const typeof mod-val ptr-mod variable)))
                                                  (format t "RRRRR5 ~A~%" ty-def)
                                                  (values (remove nil ty-def) ty-def))))))
                                         ((and (= (length clause) 2) (find func *unaries* :test #'key-eq))
                                          (return-from infer-type (infer-type (cadr clause)
                                                                    :with-name with-name :copy-name copy-name)))
                                         ((and (> (length clause) 2) (find func *operators* :test #'key-eq))
                                          (return-from infer-type (infer-type (cadr clause)
                                                                    :with-name with-name :copy-name copy-name)))
                                         ((key-eq func '->)
                                          (let ((struct (nth-value 1 (infer-type (cadr clause)
                                                                       :with-name with-name :copy-name copy-name))))
                                            (format t "SSSSSS1 ~A~%" struct)
                                            (when struct
                                              (format t "STRUCTTTT1II-> ~A  ~A~%" (typep (nth 1 struct) 'sp) struct)
                                              (let ((end-type (if (typep (nth 1 struct) 'sp)
                                                                  (deep-typeof id (nth 1 struct))
                                                                  (deep-typeof (nth 1 struct)))))
                                                (unless end-type (error "unknown struct type: ~A~%  accessed in: ~A~%" struct clause))
                                                (format t "STRUCTTTT2II-> ~A~%" end-type)
                                                (return-from infer-type
                                                  (infer-type-spec
                                                      ""
                                                    (*gets* (intern (format nil "~A/~A"  (caddr clause) (typeof end-type))))))))))
                                         ((key-eq func '$)
                                          (let ((struct (nth-value 1 (infer-type (cadr clause)
                                                                       :with-name with-name :copy-name copy-name))))
                                            (format t "SSSSSS2 ~A~%" struct)
                                            (when struct
                                              (format t "STRUCTTTT1PII ~A~%" struct)
                                              (let ((end-type (if (typep (nth 1 struct) 'sp)
                                                                  (deep-typeof id (nth 1 struct))
                                                                  (deep-typeof (nth 1 struct)))))
                                                (unless end-type (error "unknown struct type: ~A~%  accessed in: ~A~%" struct clause))
                                                (format t "STRUCTTTT2PII ~A~%" end-type)
                                                (return-from infer-type
                                                  (infer-type-spec
                                                      ""
                                                    (*gets* (intern (format nil "~A/~A"  (caddr clause) (typeof end-type))))))))))
                                         ((key-eq func '|return|) (return-from infer-type
                                                                    (infer-type (cadr clause)
                                                                      :with-name with-name :copy-name copy-name)))
                                         ((key-eq func '?) (return-from infer-type
                                                             (infer-type (caddr clause)
                                                               :with-name with-name :copy-name copy-name)))
                                         ((symbolp func) ; a function call or type descriptor
                                          (let ((ty (*gets* func)))
                                            (cond ((key-eq (construct ty) '|@FUNC|) ty)
                                                  ((key-eq (construct ty) '|@STRUCT|)
                                                   (multiple-value-bind (const typeof modifier const-ptr variable array)
		                                               (specify-type< clause)
                                                     (let ((ty-def (list const typeof modifier const-ptr variable array)))
                                                       (format t "RRRRR6 ~A~%" ty-def)
                                                       (return-from infer-type (values (remove nil ty-def) ty-def)))))
                                                  (t ty))))
                                         ) ; cond
                                   ))
                     (t (deep-typeof id)))))
    (if spec
        (infer-type-spec id spec :with-name with-name :copy-name copy-name)
        (error (format nil "type inference failed for: ~A" id)))))

(defun find-clause (func tree)
  (if (atom tree)
      nil
      (if (and (symbolp (car tree)) (key-eq (car tree) func))
          tree
          (dolist (node tree)
            (let ((ret-val (find-clause func node))) 
              (when ret-val (return-from find-clause ret-val)))))))

(defun find-attr (spec attr)
  (let ((atts (attrs spec)))
    (find attr atts :test #'(lambda (at kv) (when (key-eq at (car kv)) kv)))))

(defun is-non-copy (id)
  (let ((origin (if (typep id 'sp) (deep-typeof "" id) (deep-typeof id))))
    (when (and origin (key-eq (construct origin) '|@STRUCT|) (find-attr origin '|non-copy|))
      t)))

(defun is-inside-loop ()
  (dolist (lex-id *lexemes-id*)
    (when (or (str:starts-with-p "for"   lex-id)
              (str:starts-with-p "while" lex-id)
              (str:starts-with-p "do"    lex-id))
      (return-from is-inside-loop t))))

(defun assign-check (spec left right)
  (let ((initializing (when (find (construct spec) '(|@VAR| |@PARAM| |@LET| |@LETN| |@FUNC|)) t))
        (left-type (deep-typeof "" left)))
    (format t "CHECKLEFT ~A   ~A~%" initializing left-type)
    (if left-type
        (unless (or (and initializing (modifier left-type))
                    (and (modifier left-type) (not (key-eq (modifier left-type) '|move|))))
          (let ((left-origin (if (typep (typeof left-type) 'sp)
                                 (deep-typeof "" (typeof left-type))
                                 (deep-typeof (typeof left-type)))))
            (when (and left-origin (or (null right) (not (key-eq (name right) '|LETNMOVECAST|)))
                       (key-eq (construct left-origin) '|@STRUCT|) (find-attr left-origin '|non-copy|))
              (error (format nil "non-copy struct assignment for: ~A~%  by: ~A~%  inside: ~A~%" left right spec )))))
        (when right
          (let ((right-type (deep-typeof "" right)))
            (format t "CHECKRIGHT ~A   ~A~%" initializing right-type)
            (when right-type
              (unless (or (and initializing (modifier left-type))
                          (and (modifier right-type) (not (key-eq (modifier right-type) '|move|))))
                (let ((right-origin (if (typep (typeof right-type) 'sp)
                                 (deep-typeof "" (typeof right-type))
                                 (deep-typeof (typeof right-type)))))
                  (when (and right-origin (not (key-eq (name right-origin) '|LETNMOVECAST|))
                             (key-eq (construct right-origin) '|@STRUCT|) (find-attr right-origin '|non-copy|))
                    (error (format nil "non-copy struct assignment for: ~A~%  by: ~A~%  inside: ~A~%" left right spec )))))))))))

(defun move-var (spec inside)
  (let ((origin (deep-storageof-name "" (list (name spec)) spec))) ; check for moved vars
    (format t "CCCCCCCCCCCCCCCCCCC1 ~A~%  SPECCCC ~A~%" origin spec)
    (if (and origin
             (find (construct origin) '(|@VAR| |@PARAM|))
             (or (key-eq (modifier origin) '|move|)
                 (key-eq (modifier origin) '|ref|)))
        (progn
          (format t "CCCCCCCCCCCCCCCCCCC2 ~A~%" (is-moved origin))
          (if (is-moved origin)
              (error (format nil "trying to move already moved var: ~A~%  in call: ~A~%  moved before here: ~A~%"
                             origin inside (is-moved origin)))
              (if (and (key-eq (modifier origin) '|move|) (is-inside-loop))
                  (error (format nil "using 'move var: ~A~%  inside loop~%  in call: ~A"
                                 origin inside))
                  (if (key-eq (modifier origin) '|move|)
                      (let* ((moved-name (GENSYM "moved_var"))
                             (moved-var (make-specifier moved-name '|@VAR| nil (typeof origin) nil nil nil spec '()))
                             (call-var (make-specifier (specify-symbol-expr '|memset|) '|@CALL| nil nil nil nil nil
                                                       (list (make-specifier '|&| '|@UNARY| nil nil nil nil nil spec '())
                                                             (make-specifier 0 '|@ATOM| nil '|@NUMBER| nil nil nil nil '())
                                                             (make-specifier nil '|@SIZEOF| nil nil nil nil nil spec '()))
                                                       '()))
                             (let-var (make-specifier (GENSYM "letnmove") '|@LETN| nil nil nil nil nil nil '()))
                             (body-var (make-specifier (GENSYM "bodymove") '|@BODY| nil nil nil nil nil nil '())))
                        (setf (is-moved origin) inside)
                        (add-param moved-var let-var)
                        (setf (body body-var) (list call-var (make-specifier moved-name '|@ATOM| nil '|@SYMBOL| nil nil nil nil '())))
                        (setf (body let-var) body-var)
                        (make-specifier '|LETNMOVECAST| '|@CAST| nil (typeof origin) '|move| nil nil let-var '())
                        ) ; copy, set zero moved arg, pass 
                      spec))))
        spec)))

;; a way to make DEFMACRO statically typed
(defun type-check (value &key const typeof modifier const-ptr has-name with-name copy-name)
  (let ((value (expand-macros value)))
    (multiple-value-bind (desc-type full-type) (infer-type value :with-name with-name :copy-name copy-name)
      (FORMAT T "TYPE-CHECK: ~A~%        , ~A~%"
              (list value const typeof modifier const-ptr has-name with-name copy-name)
              full-type)
      (when const
        (when (atom const) (setq const (list const)))
        (unless (find (nth 0 full-type) const :test #'key-eq)
          (error (format nil "type-check: invalid const value: ~A~%  of: ~A~%  for: ~A" const full-type value))))
      (when typeof
        (when (typep (nth 1 full-type) 'sp)
          (multiple-value-setq (desc-type full-type) (infer-type-spec ""
                                                       (combine-types (nth 1 full-type) full-type)
                                                       :with-name with-name :copy-name copy-name)))
        (when (atom typeof) (setq typeof (list typeof)))
        (setq typeof (loop for symb in typeof
                           collect (intern (substitute #\_ #\^ (symbol-name (expand-macros symb))))))
        (let* ((cur-type (nth 1 full-type))
               (origin (if (typep cur-type 'sp)
                           (deep-typeof "" (*gets* `(<> ,(typeof (deep-typeof "" cur-type T)) |type_t|)))
                           (deep-typeof "" (*gets* `(<> ,(typeof (*gets* cur-type)) |type_t|)) T))))
          (format t "TTTTTTTTTTTTTTTTOF ~A~%" origin)
          (unless (and origin (find (typeof origin) typeof :test #'key-eq))
            (error (format nil "type-check: invalid type value: ~A~%  of: ~A~%  for: ~A" typeof full-type value)))))
      (when modifier
        (when (atom modifier) (setq modifier (list modifier)))
        (unless (find (if (nth 2 full-type) (nth 2 full-type) '|nil|) modifier :test #'key-eq)
          (error (format nil "type-check: invalid modifier value: ~A~%  of: ~A~%  for: ~A" modifier full-type value))))
      (when const-ptr
        (when (atom const-ptr) (setq const-ptr (list const-ptr)))
        (unless (find (nth 3 full-type) const-ptr :test #'key-eq)
          (error (format nil "type-check: invalid const-ptr value: ~A~%  of: ~A~%  for: ~A" const-ptr full-type value))))
      (when has-name
        (unless (nth 4 full-type)
          (error (format nil "type-check: missing name of: ~A~%  for: ~A" full-type value))))
      (values desc-type full-type))))
