(in-package :cicili)

(defun format-type-value (const typeof modifier const-ptr name array-def default anonymous lvl globals &optional defer)
  (when anonymous (setq name (format nil "/* ~A */" name)))
  (let ((ns (multiple-value-list
                (format-type const typeof modifier const-ptr name array-def anonymous lvl globals))))

    (when defer
      (output " ")
      (set-ast-line (output "__attribute__(("))
      (set-ast-line (output "__cleanup__("))
      (compile-form defer (1+ lvl) globals)
      (set-ast-line (output ")))")))
    
    (when (and (not (null default)) (not (key-eq (construct default) '|@NIL|)))
      (output " ")
      (set-ast-line (output "= "))

      (let* ((line-n   (nth 0 ns))
             (col-n    (nth 1 ns))
             (ast      (prev-ast-by-key< (gethash 'key-def (keys default))))
             (info     (getf ast 'info))
             (dump     (reverse (getf ast 'dump)))
             (spec-key (ast-key< line-n col-n))
             (res      (gethash 'res-def (keys default))))
        (setf (gethash 'key-def (keys default)) spec-key)
        (when *debug-resolve*
          (display "resolving def:" line-n col-n "RES:" res "INFO:" info #\Newline dump #\Newline))
        
        (cond ((null ast)
	           (compile-form default (1+ lvl) globals))
              (res
               (set-ast-line (output "~A" res))
               (set-ast-line (output "("))
               (compile-form default (1+ lvl) globals)
               (output ")"))
              ((str:containsp "incompatible pointer types" info)
               (let* ((result (multiple-value-list (ppcre:scan-to-strings *trait-regex* info)))
                      (matches (cadr result)))
                 (let ((resu (make-shared-name (elt matches 1) (format nil "to~A" (elt matches 0)))))
                   (if (gethash (intern resu) *globals*)
                       (progn
                         (setf (gethash 'res-def (keys default)) resu)
                         (set-ast-line (output "~A" resu))
                         (set-ast-line (output "("))
                         (compile-form default (1+ lvl) globals)
                         (output ")"))
                       (error (format nil "undefined trait: ~A" result))))))
              ((str:containsp "format specifies type" info)
               (let* ((result (multiple-value-list (ppcre:scan-to-strings *trait-regex* info)))
                      (matches (cadr result)))
                 (let ((resu (make-shared-name (elt matches 0) (format nil "to~A" (elt matches 1)))))
                   (if (gethash (intern resu) *globals*)
                       (progn
                         (setf (gethash 'res-def (keys default)) resu)
                         (set-ast-line (output "~A" resu))
                         (set-ast-line (output "("))
                         (compile-form default (1+ lvl) globals)
                         (output ")"))
                       (error (format nil "undefined trait: ~A" default))))))
              (t (compile-form default (1+ lvl) globals)))))))

(defun compile-symbol (spec symbol)
  (let* ((line-n   (funcall *line-num* 0))
         (col-n    (funcall *col-num* 0))
         (ast      (prev-ast-by-key< (gethash 'key-sym (keys spec))))
         (info     (getf ast 'info))
         (spec-key (ast-key< line-n col-n))
         (res      (gethash 'res-sym (keys spec))))
    (setf (gethash 'key-sym (keys spec)) spec-key)
    (when *debug-resolve*
      (display "resolving symbol:" line-n col-n "RES:" res "INFO:" info #\Newline))
    (if (null ast)
	    (set-ast-line (output "~A " symbol))
        (if info
            (cond ((str:containsp "take the address with &" info)
                   (let ((resu (format nil "\&~A" symbol)))
                     (setf (gethash 'res-sym (keys spec)) resu)
                     (set-ast-line (output resu))))
                  ((str:containsp "passing 'typeof ((" info)
                   (let ((resu (format nil "\&~A" symbol)))
                     (setf (gethash 'res-sym (keys spec)) resu)
                     (set-ast-line (output resu))))
                  ((str:containsp "__ciciliL_" info)
                   (let ((resu (format nil "\&~A" symbol)))
                     (setf (gethash 'res-sym (keys spec)) resu)
                     (set-ast-line (output resu))))
                  ((str:containsp "expression result unused" info)
                   (let ((resu (format nil "~A " symbol)))
                     (setf (gethash 'res-sym (keys spec)) resu)
                     (set-ast-line (output resu))))
                  ((str:containsp "member reference type" info)
                   (let ((resu (format nil "~A " symbol)))
                     (setf (gethash 'res-sym (keys spec)) resu)
                     (set-ast-line (output resu))))
                  ((str:containsp "no member named" info)
                   (set-ast-line (output "~A " symbol))) ; ignore for ->
                  ((str:containsp "format specifies type" info)
                   (set-ast-line (output "~A " symbol))) ; ignore for arg
                  ((str:containsp "incompatible pointer types" info)
                   (set-ast-line (output "~A " symbol))) ; ignore for arg
                  (t (error (format nil "cicili: atom: ~A. ~S~%~A" spec-key (str:substring 0 340 info) spec))))
            (if (null res)
                (set-ast-line (output "~A " symbol))
                (set-ast-line (output res)))))))

(defun compile-$ (spec lvl globals)
  (with-slots ((receiver name) (member default)) spec
    (let* ((line-n     (funcall *line-num* 0))
           (col-n      (funcall *col-num* 0))
           (begin-ast  (prev-ast-by-key< (gethash 'key-$ (keys spec))))        ; --
           (ptr-ast    (prev-ast-by-key< (getf begin-ast 'ptr)))
           (mtd-ast    (prev-ast-by-key< (getf begin-ast 'mtd)))
           (end-ast    (prev-ast-by-key< (getf begin-ast 'end)))
           (begin-info (getf begin-ast 'info)) ; --
           (begin-dump (reverse (getf begin-ast 'dump))) ; --
           
           (ptr-info   (getf ptr-ast   'info))
           (mtd-info   (getf mtd-ast   'info))
           (end-info   (getf end-ast   'info))
           (spec-key   (ast-key< line-n col-n))
           (res        (gethash 'res-$ (keys spec))))
      (setf (gethash 'key-$ (keys spec)) spec-key)
      (when *debug-resolve*
        (display "resolving .:" line-n col-n "RES:" res "INFO:"
                 begin-info ptr-info mtd-info end-info #\Newline begin-dump #\Newline))
      
      (cond (res
             (set-ast-line (output "("))
             (compile-form receiver (1+ lvl) globals)
             (set-ast-line (output res))
             (compile-form member (1+ lvl) globals)
             (output ")"))
            ((or (null *resolve*) ; function without resolver (inline in header or attr resolve #f)
               (null begin-ast)  ; access member by instance default for first run
               (and (null begin-info) (null ptr-info) (null mtd-info) (null end-info)))
             (set-ast-line (output "("))
             (compile-form receiver (1+ lvl) globals)
             (setf (getf (gethash (ast-key< line-n col-n) (nth 0 *ast-lines*)) 'ptr)
                   (ast-key< (funcall *line-num* 0) (funcall *col-num* 0)))
             (set-ast-line (output ". "))
             (setf (getf (gethash (ast-key< line-n col-n) (nth 0 *ast-lines*)) 'mtd)
                   (ast-key< (funcall *line-num* 0) (funcall *col-num* 0)))
             (compile-form member (1+ lvl) globals)
             (setf (getf (gethash (ast-key< line-n col-n) (nth 0 *ast-lines*)) 'end)
                   (ast-key< (funcall *line-num* 0) (funcall *col-num* 0)))
             (output ")"))
            ((and (str:containsp "member reference type" ptr-info) (str:containsp "is a pointer" ptr-info))
             (let ((resu "->"))
               (setf *more-run* t)
               (setf (gethash 'res-$ (keys spec)) resu)
               (set-ast-line (output "("))
               (compile-form receiver (1+ lvl) globals)
               (set-ast-line (output resu))
               (compile-form member (1+ lvl) globals)
               (output ")")))
            (t (error (format nil "cicili\: unresolved member reference type ~A. ~S~%~A"
                              spec-key (str:substring 0 340 (or mtd-info ptr-info begin-info)) spec)))))))

(defun compile--> (spec lvl globals)
  (with-slots ((receiver name) (method default) (args body)) spec
    (let* ((line-n     (funcall *line-num* 0))
           (col-n      (funcall *col-num* 0))
           (begin-ast  (prev-ast-by-key< (gethash 'key--> (keys spec))))        ; --
           (ptr-ast    (prev-ast-by-key< (getf begin-ast 'ptr)))
           (mtd-ast    (prev-ast-by-key< (getf begin-ast 'mtd)))
           (end-ast    (prev-ast-by-key< (getf begin-ast 'end)))
           (begin-info (getf begin-ast 'info)) ; --
           (begin-dump (reverse (getf begin-ast 'dump))) ; --
           
           (ptr-info   (getf ptr-ast   'info))
           (mtd-info   (getf mtd-ast   'info))
           (end-info   (getf end-ast   'info))
           (spec-key   (ast-key< line-n col-n))
           (res        (gethash 'res--> (keys spec))))
      (setf (gethash 'key--> (keys spec)) spec-key)
      (when *debug-resolve*
        (display "resolving ->:" line-n col-n "RES:" res "INFO:" 
                 begin-info ptr-info mtd-info end-info #\Newline begin-dump #\Newline))
      
      (cond (res
             (if (str:starts-with-p (str:replace-first "\\(.*" "" (make-shared-name (name receiver) "") :regex t)
                   res) ; was shared or method
                 (progn
                   (set-ast-line (output res))
                   (output "(")
                   (compile-args (default args) lvl globals nil)
                   (setf (getf (gethash (ast-key< line-n col-n) (nth 0 *ast-lines*)) 'end)
                         (ast-key< (funcall *line-num* 0) (funcall *col-num* 0)))
                   (output ")"))
                 (progn
                   (set-ast-line (output res))
                   (output "(")
                   (compile-form receiver (1+ lvl) globals)
                   (compile-args (default args) lvl globals t)
                   (setf (getf (gethash (ast-key< line-n col-n) (nth 0 *ast-lines*)) 'end)
                         (ast-key< (funcall *line-num* 0) (funcall *col-num* 0)))
                   (output ")"))))
            ((or (null *resolve*) ; function without resolver (inline in header or attr resolve #f)
               (null begin-ast)  ; access member by pointer default for first run
               (and (null begin-info) (null ptr-info) (null mtd-info) (null end-info)))
             (set-ast-line (output "("))
             (compile-form receiver (1+ lvl) globals)
             (setf (getf (gethash (ast-key< line-n col-n) (nth 0 *ast-lines*)) 'ptr)
                   (ast-key< (funcall *line-num* 0) (funcall *col-num* 0)))
             (set-ast-line (output "->"))
             (setf (getf (gethash (ast-key< line-n col-n) (nth 0 *ast-lines*)) 'mtd)
                   (ast-key< (funcall *line-num* 0) (funcall *col-num* 0)))
             (compile-form method (1+ lvl) globals)
             (compile-args (default args) lvl globals t)
             (setf (getf (gethash (ast-key< line-n col-n) (nth 0 *ast-lines*)) 'end)
                   (ast-key< (funcall *line-num* 0) (funcall *col-num* 0)))
             (output ")"))
            ((and ptr-info (str:containsp "expected ')'" ptr-info))
             (let ((resu (make-shared-name (name receiver) (name method))))
               (if (gethash (intern resu) *globals*)
                   (progn
                     (setf *more-run* t)               
                     (setf (gethash 'res--> (keys spec)) resu)
                     (set-ast-line (output "~A" resu))
                     (output "(")
                     (compile-args (default args) lvl globals nil)
                     (output ")"))
                   (error (format nil "undefined function: ~A" spec)))))
            ((and ptr-info (str:containsp "expected expression" ptr-info))
             (if (key-eq (construct receiver) '|@ATOM|) 
                 (let ((resu (make-method-name (name receiver) (name method))))
                   (if (gethash (intern resu) *globals*)
                       (progn
                         (setf *more-run* t)               
                         (setf (gethash 'res--> (keys spec)) resu)
                         (set-ast-line (output resu))
                         (output "(")
                         (compile-form receiver (1+ lvl) globals)
                         (compile-args (default args) lvl globals t)
                         (output ")"))
                       (error (format nil "undefined function: ~A" spec))))
                 (progn
                   (set-ast-line (output "("))
                   (compile-form receiver (1+ lvl) globals)
                   (setf (getf (gethash (ast-key< line-n col-n) (nth 0 *ast-lines*)) 'ptr)
                         (ast-key< (funcall *line-num* 0) (funcall *col-num* 0)))
                   (set-ast-line (output "->"))
                   (setf (getf (gethash (ast-key< line-n col-n) (nth 0 *ast-lines*)) 'mtd)
                         (ast-key< (funcall *line-num* 0) (funcall *col-num* 0)))
                   (compile-form method (1+ lvl) globals)
                   (compile-args (default args) lvl globals t)
                   (setf (getf (gethash (ast-key< line-n col-n) (nth 0 *ast-lines*)) 'end)
                         (ast-key< (funcall *line-num* 0) (funcall *col-num* 0)))
                   (output ")"))))
            ((and end-info (str:containsp "too few arguments" end-info))
             (error (format nil "cicili\: call: ~S" (str:substring 0 330 end-info))))
            ((and mtd-info (str:containsp "no member named" mtd-info))
             (let* ((matches     (ppcre:all-matches-as-strings "'(struct\\s+)?\\w+'" mtd-info))
                    (method      (car matches))
                    (parts       (str:split #\Space (cadr matches)))
                    (resu        (make-method-name (string-right-trim "'" (cadr parts)) (string-trim "'" method))))
               (if (string-equal (car parts) "'struct")
                   (if (gethash (intern resu) *globals*)
                       (progn
                         (setf *more-run* t)               
                         (setf (gethash 'res--> (keys spec)) resu))
                       (error (format nil "undefined function: ~A" spec)))
                   (error (format nil "cicili\: nnn unresolved method reference type ~A. ~s~%~A"
                                  spec-key (str:substring 0 340 (or mtd-info ptr-info begin-info)) spec)))
               (set-ast-line (output "~A" resu))
               (output "(")
               (compile-form receiver lvl globals)
               (compile-args (default args) lvl globals t)
               (output ")")))
            (t (error (format nil "cicili\: unresolved method reference type ~A. ~S~%~A"
                              spec-key (str:substring 0 340 (or mtd-info ptr-info begin-info)) spec)))))))

(defun compile-args (args lvl globals comma-first)
  (when (and comma-first (> (length args) 0)) (output ", "))
  (loop for arg in args
        with l = (1- (length args))
        for i from 0 to l
        do (progn
             (let* ((line-n   (funcall *line-num* 0))
                    (col-n    (funcall *col-num* 0))
                    (ast      (prev-ast-by-key< (gethash 'key-arg (keys arg))))
                    (info     (getf ast 'info))
                    (dump     (reverse (getf ast 'dump)))
                    (spec-key (ast-key< line-n col-n))
                    (res      (gethash 'res-arg (keys arg))))
               (setf (gethash 'key-arg (keys arg)) spec-key)
               (when *debug-resolve*
                 (display "resolving arg:" line-n col-n "RES:" res "INFO:" info #\Newline dump #\Newline))
               
               (cond ((null ast)
	                  (compile-form arg lvl globals))
                     (res
                      (set-ast-line (output "~A" res))
                      (set-ast-line (output "("))
                      (compile-form arg lvl globals)
                      (output ")"))
                     ((str:containsp "incompatible pointer types" info)
                      (let* ((result (multiple-value-list (ppcre:scan-to-strings *trait-regex* info)))
                             (matches (cadr result)))
                        (let ((resu (make-shared-name (elt matches 0) (format nil "to~A" (elt matches 1)))))
                          (if (gethash (intern resu) *globals*)
                              (progn
                                (setf (gethash 'res-arg (keys arg)) resu)
                                (set-ast-line (output "~A" resu))
                                (set-ast-line (output "("))
                                (compile-form arg lvl globals)
                                (output ")"))
                              (error (format nil "undefined trait: ~A" spec))))))
                     ((str:containsp "format specifies type" info)
                      (let* ((result (multiple-value-list (ppcre:scan-to-strings *trait-regex* info)))
                             (matches (cadr result)))
                        (let ((resu (make-shared-name (elt matches 1) (format nil "to~A" (elt matches 0)))))
                          (if (gethash (intern resu) *globals*)
                              (progn                                
                                (setf (gethash 'res-arg (keys arg)) resu)
                                (set-ast-line (output "~A" resu))
                                (set-ast-line (output "("))
                                (compile-form arg lvl globals)
                                (output ")"))
                              (error (format nil "undefined trait: ~A" spec))))))
                     ((str:containsp "member reference type" info)
                      (compile-form arg lvl globals))
                     (t (compile-form arg lvl globals))))
             (when (< i l) (output ", ")))))

(defun compile-set (spec lvl globals)
  (with-slots ((items default)) spec
    (dolist (item items)
      (when (> lvl -1) (output "~&~A" (indent lvl)))
      (compile-form (nth 0 item) (1+ lvl) globals)
      (output " ")

      (let* ((line-n   (funcall *line-num* 0))
             (col-n    (funcall *col-num* 0))
             (ast      (prev-ast-by-key< (gethash 'key-set (keys (nth 1 item)))))
             (info     (getf ast 'info))
             (dump     (reverse (getf ast 'dump)))
             (spec-key (ast-key< line-n col-n))
             (res      (gethash 'res-set (keys (nth 1 item)))))
        (setf (gethash 'key-set (keys (nth 1 item))) spec-key)
        (when *debug-resolve*
          (display "resolving set:" line-n col-n "RES:" res "INFO:" info #\Newline dump #\Newline))
        
        (cond ((null ast)
               (set-ast-line (output "= "))
	           (compile-form (nth 1 item) (1+ lvl) globals))
              (res
               (set-ast-line (output "= "))
               (set-ast-line (output "~A" res))
               (set-ast-line (output "("))
               (compile-form (nth 1 item) (1+ lvl) globals)
               (output ")"))
              ((str:containsp "incompatible pointer types" info)
               (let* ((result (multiple-value-list (ppcre:scan-to-strings *trait-regex* info)))
                      (matches (cadr result)))
                 (let ((resu (make-shared-name (elt matches 1) (format nil "to~A" (elt matches 0)))))
                   (if (gethash (intern resu) *globals*)
                       (progn
                         (setf (gethash 'res-set (keys (nth 1 item))) resu)
                         (set-ast-line (output "= "))
                         (set-ast-line (output "~A" resu))
                         (set-ast-line (output "("))
                         (compile-form (nth 1 item) (1+ lvl) globals)
                         (output ")"))
                       (error (format nil "undefined trait: ~A" spec))))))
              ((str:containsp "format specifies type" info)
               (let* ((result (multiple-value-list (ppcre:scan-to-strings *trait-regex* info)))
                      (matches (cadr result)))
                 (let ((resu (make-shared-name (elt matches 0) (format nil "to~A" (elt matches 1)))))
                   (if (gethash (intern resu) *globals*)
                       (progn
                         (setf (gethash 'res-set (keys (nth 1 item))) resu)
                         (set-ast-line (output "= "))
                         (set-ast-line (output "~A" resu))
                         (set-ast-line (output "("))
                         (compile-form (nth 1 item) (1+ lvl) globals)
                         (output ")"))
                       (error (format nil "undefined trait: ~A" spec))))))
              (t (set-ast-line (output "= "))
	             (compile-form (nth 1 item) (1+ lvl) globals))))
      (when (> lvl -1) (output ";~%")))))
