;;;; Cicili std rc
(generic decl-rc
  (type a)

  (struct type
          (member uintptr_t ptr)
          (member size_t    adr))
  
  (typedef a (<> type interior_t))

  (inline)
  (func (<> free type) ((type * rc))
        (when (and (-> rc ptr) (== (cof (cast (size_t *) (-> rc ptr))) (-> rc adr))) ; liveness
          (syslog! (printf "FREE RC: %p %p %zx\n" (cof (cast (size_t **) (-> rc ptr))) (cast (void *) (-> rc ptr)) (-> rc adr)))
          (let ((size_t counter . (FUNCTION (cof (cast (size_t *) (+ (cast (uintptr_t *) (-> rc ptr)) 1))))))
            (syslog! (printf "FREE RC: counter: %zu\n" counter))
            (if (> counter 1)
                (-- (cof (cast (size_t *) (+ (cast (uintptr_t *) (-> rc ptr)) 1))))
                (when (== counter 1)
                  ((<> free a) (cof (cast (a **) (-> rc ptr))))
                  (free (cof (cast (void **) (-> rc ptr))))
                  (set (cof (cast (uintptr_t **) (-> rc ptr))) 0)
                  (free (cast (void *) (-> rc ptr)))
                  (set (-> rc ptr) 0))))))

  (inline)
  (func (<> force free a) ((a * obj))
        ((<> free a) obj))

  ;; interior guard
  (DEFMACRO (<> free a) (obj)
    (ERROR (FORMAT NIL "shouldn't free an object where ordered to be used inside Rc: ~A" (symbol-name a))))
  
  ) ; decl-rc

(DEFMACRO free^rc (rc)
  (LET ((rc rc)
        (type (CICILI:INFER-TYPE rc)))
    (WHEN (OR (/= (LENGTH type) 2) (NOT (EQL (CADR type) '*))) (ERROR (FORMAT NIL "free rc got invalid type ~A for ~A" type rc)))
    `((<> free ,(CAR type)) ,rc)))


(DEFMACRO new^rc (type &REST args)
  (LET* ((ctor `(<> new ,type))
         (args args)
         (a (CICILI:INFER-TYPE `(,ctor ,@args)))
         (ptr-name (GENSYM "tmp_ptr"))
         (dptr-name (GENSYM "tmp_rc_ptr")))
    (WHEN (> (LENGTH a) 1) (ERROR (FORMAT NIL "new rc got invalid type ~A for ~A" a ctor)))
    `(letn ((,@a * ,ptr-name . (FUNCTION (malloc (sizeof ,@a))))
            (uintptr_t * ,dptr-name . (FUNCTION (malloc (+ (sizeof uintptr_t) (sizeof size_t))))))
       (set (cof ,ptr-name) (,ctor ,@args))
       (set (cof ,dptr-name) (cast uintptr_t ,ptr-name))
       (set (cof (cast (size_t *) (+ ,dptr-name 1))) 1)
       (syslog! (printf "NEW RC: %p %zx %zx\n" ,ptr-name (cast uintptr_t ,dptr-name) (cof (cast (size_t *) ,dptr-name))))
       (cast (<> rc ,@a) '{ (cast uintptr_t ,dptr-name) (cof (cast (size_t *) ,dptr-name)) }))))


(DEFMACRO let^rc ((obj rc &REST captures) &REST body)
  (LET* ((obj obj)
         (rc rc)
         (type (CICILI:INFER-TYPE rc))
         (rc-acc (GENSYM "acc_rc"))
         (rc-ptr (GENSYM "acc_rc_ptr")))
    (WHEN (> (LENGTH type) 1) (ERROR (FORMAT NIL "let rc got invalid type ~A for ~A" type rc)))
    `(closure ((<> let ,@type ,(GENSYM)) ,rc-acc ,rc ,@captures)
       (let (((<> ,@type interior_t) ** ,rc-ptr . (FUNCTION (cast ((<> ,@type interior_t) **) ($ ,rc-acc ptr)))))
         (when (and ,rc-ptr (== (cof (cast (size_t *) ,rc-ptr)) ($ ,rc-acc adr)))
           (let (((<> ,@type interior_t) ,obj . (FUNCTION (cof (cof ,rc-ptr)))))
             ,@body))))))


(DEFMACRO letn^rc ((obj rc default &REST captures) &REST body)
  (LET* ((obj obj)
         (rc rc)
         (default default)
         (type (CICILI:INFER-TYPE rc))
         (rc-acc (GENSYM "acc_rc"))
         (rc-ptr (GENSYM "acc_rc_ptr")))
    (WHEN (> (LENGTH type) 1) (ERROR (FORMAT NIL "letn rc got invalid type ~A for ~A" type rc)))
    `(closure ((<> letn ,@type ,(GENSYM)) ,rc-acc ,rc :default_value ,default ,@captures)
       (out auto)
       (return (letn (((<> ,@type interior_t) ** ,rc-ptr . (FUNCTION (cast ((<> ,@type interior_t) **) ($ ,rc-acc ptr)))))
                 (? (and ,rc-ptr (== (cof (cast (size_t *) ,rc-ptr)) ($ ,rc-acc adr)))
                   (letn (((<> ,@type interior_t) ,obj . (FUNCTION (cof (cof ,rc-ptr)))))
                     ,@body)
                   default_value))))))


(DEFMACRO clone^rc (rc)
  (LET* ((rc rc)
         (type (CICILI:INFER-TYPE rc))
         (rc-acc (GENSYM "acc_rc"))
         (rc-ptr (GENSYM "acc_rc_ptr")))
    (WHEN (> (LENGTH type) 1) (ERROR (FORMAT NIL "clone rc got invalid type ~A for ~A" type rc)))
    `(closure ((<> clone ,@type ,(GENSYM)) ,rc-acc ,rc)
       (out ,@type)
       (return (letn (((<> ,@type interior_t) ** ,rc-ptr . (FUNCTION (cast ((<> ,@type interior_t) **) ($ ,rc-acc ptr)))))
                 (when (and ,rc-ptr (== (cof (cast (size_t *) ,rc-ptr)) ($ ,rc-acc adr)))
                   (++ (cof (cast (size_t *) (+ (cast (uintptr_t *) ,rc-ptr) 1)))))
                 ,rc-acc)))))


(DEFMACRO take^rc ((ptr rc &REST captures) &REST body)
  (LET* ((ptr ptr)
         (rc rc)
         (type (CICILI:INFER-TYPE rc))    
         (rc-acc (GENSYM "acc_rc"))
         (rc-ptr (GENSYM "acc_rc_ptr")))
    (WHEN (> (LENGTH type) 1) (ERROR (FORMAT NIL "take rc got invalid type ~A for ~A" type rc)))
    `(closure ((<> take ,@type ,(GENSYM)) ,rc-acc ,rc ,@captures)
       (let (((<> ,@type interior_t) ** ,rc-ptr . (FUNCTION (cast ((<> ,@type interior_t) **) ($ ,rc-acc ptr)))))
         (when (and ,rc-ptr (== (cof (cast (size_t *) ,rc-ptr)) ($ ,rc-acc adr))
                    (== (cof (cast (size_t *) (+ (cast (uintptr_t *) ($ ,rc-acc ptr)) 1))) 1))
           (let (((<> ,@type interior_t) * ,ptr . (FUNCTION (cof ,rc-ptr))))
             (syslog! (printf "TAKE RC: %zx %zx\n" (cof (cast (size_t *) ,rc-ptr)) ($ ,rc-acc adr)))             
             (free (cast (void *) ($ ,rc-acc ptr)))
             (set ($ ,rc-acc ptr) 0)
             ,@body))))))


(DEFMACRO taken^rc ((ptr rc default &REST captures) &REST body)
  (LET* ((ptr ptr)
         (rc rc)
         (default default)
         (type (CICILI:INFER-TYPE rc))    
         (rc-acc (GENSYM "acc_rc"))
         (rc-ptr (GENSYM "acc_rc_ptr")))
    (WHEN (> (LENGTH type) 1) (ERROR (FORMAT NIL "taken rc got invalid type ~A for ~A" type rc)))
    `(closure ((<> taken ,@type ,(GENSYM)) ,rc-acc ,rc :default_value ,default ,@captures)
       (out auto)
       (return (letn (((<> ,@type interior_t) ** ,rc-ptr . (FUNCTION (cast ((<> ,@type interior_t) **) ($ ,rc-acc ptr)))))
                 (? (and ,rc-ptr (== (cof (cast (size_t *) ,rc-ptr)) ($ ,rc-acc adr))
                         (== (cof (cast (size_t *) (+ (cast (uintptr_t *) ($ ,rc-acc ptr)) 1))) 1))
                   (letn (((<> ,@type interior_t) * ,ptr . (FUNCTION (cof ,rc-ptr))))
                     (syslog! (printf "TAKEN RC: %zx %zx\n" (cof (cast (size_t *) ,rc-ptr)) ($ ,rc-acc adr)))                     
                     (free (cast (void *) ($ ,rc-acc ptr)))
                     (set ($ ,rc-acc ptr) 0)
                     ,@body)
                   default_value))))))


;; exclusive mutation
(DEFMACRO excl^rc ((ptr rc &REST captures) &REST body)
  (LET* ((ptr ptr)
         (rc rc)
         (type (CICILI:INFER-TYPE rc))    
         (rc-acc (GENSYM "acc_rc"))
         (rc-ptr (GENSYM "acc_rc_ptr")))
    (WHEN (> (LENGTH type) 1) (ERROR (FORMAT NIL "excl rc got invalid type ~A for ~A" type rc)))
    `(closure ((<> take ,@type ,(GENSYM)) ,rc-acc ,rc ,@captures)
       (let (((<> ,@type interior_t) ** ,rc-ptr . (FUNCTION (cast ((<> ,@type interior_t) **) ($ ,rc-acc ptr)))))
         (when (and ,rc-ptr (== (cof (cast (size_t *) ,rc-ptr)) ($ ,rc-acc adr))
                    (== (cof (cast (size_t *) (+ (cast (uintptr_t *) ($ ,rc-acc ptr)) 1))) 1))
           (let (((<> ,@type interior_t) * ,ptr . (FUNCTION (cof ,rc-ptr))))
             (syslog! (printf "excl RC: %zx %zx\n" (cof (cast (size_t *) ,rc-ptr)) ($ ,rc-acc adr)))             
             ,@body))))))


;; exclusive mutation
(DEFMACRO excln^rc ((ptr rc default &REST captures) &REST body)
  (LET* ((ptr ptr)
         (rc rc)
         (default default)
         (type (CICILI:INFER-TYPE rc))    
         (rc-acc (GENSYM "acc_rc"))
         (rc-ptr (GENSYM "acc_rc_ptr")))
    (WHEN (> (LENGTH type) 1) (ERROR (FORMAT NIL "excln rc got invalid type ~A for ~A" type rc)))
    `(closure ((<> take ,@type ,(GENSYM)) ,rc-acc ,rc :default_value ,default ,@captures)
       (out auto)
       (return (letn (((<> ,@type interior_t) ** ,rc-ptr . (FUNCTION (cast ((<> ,@type interior_t) **) ($ ,rc-acc ptr)))))
                 (? (and ,rc-ptr (== (cof (cast (size_t *) ,rc-ptr)) ($ ,rc-acc adr))
                         (== (cof (cast (size_t *) (+ (cast (uintptr_t *) ($ ,rc-acc ptr)) 1))) 1))
                   (letn (((<> ,@type interior_t) * ,ptr . (FUNCTION (cof ,rc-ptr))))
                     (syslog! (printf "EXCLN RC: %zx %zx\n" (cof (cast (size_t *) ,rc-ptr)) ($ ,rc-acc adr)))                     
                     ,@body)
                   default_value))))))
